-- Generated from src/data/games.ts. Do not edit rows by hand.
insert into public.game_catalog (id, name, category, metric, unit, direction, benchmark, duration_sec, rule_source, rotation_index) values
  ('armadillo-en-picado', 'Armadillo en Picado', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '462', 60, 'Vídeo', 1),
  ('suricatas-del-minigolf', 'Suricatas del Minigolf', 'Velocidad contra reloj', 'Hoyos', 'hoyos', 'higher', '12,8', 30, 'Oficial', 2),
  ('golondrina-cazadora', 'Golondrina Cazadora', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '731', 60, 'Oficial', 3),
  ('piton-pi', 'Pitón Pi', 'Memoria y lógica', 'Puntos', 'puntos', 'higher', 'Sin dato', 60, 'Sin confirmar', 4),
  ('serpiente-glotona', 'Serpiente Glotona', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '25', 60, 'Oficial', 5),
  ('pinguino-escalador', 'Pingüino Escalador', 'Habilidad y arcade', 'Distancia', 'm', 'higher', '163,9 m', 60, 'Oficial', 6),
  ('rinoceronte-rompemuros', 'Rinoceronte Rompemuros', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '59', 60, 'Vídeo', 7),
  ('cuervo-contacajas', 'Cuervo Contacajas', 'Memoria y lógica', 'Niveles', 'niveles', 'higher', '19', 60, 'Oficial', 8),
  ('escarabajo-pelotero', 'Escarabajo Pelotero', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '8,80 s', 60, 'Oficial', 9),
  ('gorrion-aleteador', 'Gorrión Aleteador', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '30', 60, 'Vídeo', 10),
  ('erizo-cruzacalles', 'Erizo Cruzacalles', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '124', 40, 'Oficial', 11),
  ('burro-de-carga', 'Burro de Carga', 'Memoria y lógica', 'Puntos', 'puntos', 'higher', '41', 60, 'Oficial', 12),
  ('castor-lanzador', 'Castor Lanzador', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '54', 60, 'Vídeo', 13),
  ('topo-golfista', 'Topo Golfista', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '4,56 s', 47, 'Oficial', 14),
  ('carrera-de-galgos', 'Carrera de Galgos', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '19,06 s', 60, 'Vídeo', 15),
  ('hamster-al-volante', 'Hámster al Volante', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '15,25 s', 60, 'Vídeo', 16),
  ('bingo-de-la-oveja', 'Bingo de la Oveja', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '221', 60, 'Vídeo', 17),
  ('elefante-memorioso', 'Elefante Memorioso', 'Memoria y lógica', 'Puntos', 'puntos', 'higher', '100', 60, 'Oficial', 18),
  ('gato-pianista', 'Gato Pianista', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '157', 60, 'Vídeo', 19),
  ('lobo-lunar', 'Lobo Lunar', 'Habilidad y arcade', 'Distancia', 'm', 'higher', '91,76 m', 60, 'Vídeo + análisis', 20),
  ('vencejo-veloz', 'Vencejo Veloz', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '71', 60, 'Vídeo', 21),
  ('mariposa-pintora', 'Mariposa Pintora', 'Rapidez y multitarea', 'Colores igualados', 'colores', 'higher', '32', 60, 'Oficial', 22),
  ('raton-de-laberinto', 'Ratón de Laberinto', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '12,69 s', 60, 'Oficial', 23),
  ('nutria-lanzadora', 'Nutria Lanzadora', 'Precisión y timing', 'Puntos', 'puntos', 'higher', '950', 60, 'Vídeo', 24),
  ('flamenco-equilibrista', 'Flamenco Equilibrista', 'Habilidad y arcade', 'Supervivencia', 's', 'higher', '33,59 s', 60, 'Oficial', 25),
  ('arana-tejedora', 'Araña Tejedora', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '163', 60, 'Vídeo + análisis', 26),
  ('jardin-de-luciernagas', 'Jardín de Luciérnagas', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '129', 60, 'Vídeo + análisis', 27),
  ('abejorro-propulsado', 'Abejorro Propulsado', 'Habilidad y arcade', 'Distancia', 'm', 'higher', '264 m', 60, 'Vídeo + análisis', 28),
  ('jirafa-apiladora', 'Jirafa Apiladora', 'Precisión y timing', 'Bloques', 'bloques', 'higher', '173', 40, 'Oficial', 29),
  ('murcielago-entre-pinchos', 'Murciélago entre Pinchos', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '42', 60, 'Vídeo', 30),
  ('pulga-botadora', 'Pulga Botadora', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '69', 60, 'Vídeo + análisis', 31),
  ('gallina-aleteadora', 'Gallina Aleteadora', 'Habilidad y arcade', 'Distancia', 'm', 'higher', '190 m', 60, 'Oficial', 32),
  ('cotorra-telefonista', 'Cotorra Telefonista', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '4,5 s', 60, 'Oficial', 33),
  ('chimpance-memorion', 'Chimpancé Memorión', 'Memoria y lógica', 'Puntos', 'puntos', 'higher', '100', 60, 'Oficial', 34),
  ('canguro-trampolin', 'Canguro Trampolín', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '176', 60, 'Vídeo', 35),
  ('paloma-mensajera', 'Paloma Mensajera', 'Precisión y timing', 'Puntos', 'puntos', 'higher', '78', 60, 'Vídeo', 36),
  ('sepia-reflejos', 'Sepia Reflejos', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '16', 27, 'Oficial', 37),
  ('buho-calculador', 'Búho Calculador', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '4,72 s', 60, 'Vídeo', 38),
  ('libelula-espacial', 'Libélula Espacial', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '61', 60, 'Vídeo', 39),
  ('guepardo-derrapante', 'Guepardo Derrapante', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '143', 60, 'Vídeo', 40),
  ('anguila-electrica', 'Anguila Eléctrica', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '113', 60, 'Oficial', 41),
  ('gecko-trepador', 'Gecko Trepador', 'Habilidad y arcade', 'Distancia', 'm', 'higher', '76,8 m', 60, 'Vídeo', 42),
  ('rastro-del-caracol', 'Rastro del Caracol', 'Memoria y lógica', 'Puntos', 'puntos', 'higher', '98', 60, 'Vídeo', 43),
  ('zorro-de-los-dados', 'Zorro de los Dados', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '3,46 s', 60, 'Vídeo', 44),
  ('rana-saltarina', 'Rana Saltarina', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '554', 60, 'Vídeo', 45),
  ('cangrejo-interruptor', 'Cangrejo Interruptor', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '73', 60, 'Vídeo', 46),
  ('topo-golfista-2', 'Topo Golfista 2', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '5,78 s', 47, 'Vídeo', 47),
  ('liebre-en-la-autopista', 'Liebre en la Autopista', 'Habilidad y arcade', 'Distancia', 'm', 'higher', '1.026 m', 60, 'Vídeo', 48),
  ('ardilla-contadora', 'Ardilla Contadora', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '2,29 s', 60, 'Vídeo', 49),
  ('pajaro-carpintero', 'Pájaro Carpintero', 'Rapidez y multitarea', 'Toques', 'toques', 'higher', '139', 60, 'Oficial', 50),
  ('colibri-reflejos', 'Colibrí Reflejos', 'Velocidad contra reloj', 'Tiempo medio', 's', 'lower', '0,288 s', 15, 'Oficial', 51),
  ('medusa-a-partes-iguales', 'Medusa a Partes Iguales', 'Precisión y timing', 'Precisión', '%', 'higher', '99 %', 60, 'Oficial', 52),
  ('oso-encestador', 'Oso Encestador', 'Rapidez y multitarea', 'Canastas', 'canastas', 'higher', '33', 60, 'Oficial', 53),
  ('marmota-cronometro', 'Marmota Cronómetro', 'Precisión y timing', 'Desviación', 's', 'lower', '0,06 s', 60, 'Oficial', 54),
  ('grillo-ritmico', 'Grillo Rítmico', 'Precisión y timing', 'Precisión', '%', 'higher', '98,4 %', 60, 'Oficial', 55),
  ('hormiga-zigzag', 'Hormiga Zigzag', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '201', 60, 'Oficial', 56),
  ('ojo-de-halcon', 'Ojo de Halcón', 'Precisión y timing', 'Precisión media', '%', 'higher', '97,89 %', 60, 'Oficial', 57),
  ('camaleon-columpio', 'Camaleón Columpio', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '310', 60, 'Oficial', 58),
  ('pulpo-camuflaje', 'Pulpo Camuflaje', 'Memoria y lógica', 'Parecido', '%', 'higher', '99,18 %', 60, 'Oficial', 59),
  ('tucan-balancin', 'Tucán Balancín', 'Habilidad y arcade', 'Supervivencia', 's', 'higher', '63,87 s', 60, 'Vídeo', 60),
  ('correcaminos', 'Correcaminos', 'Velocidad contra reloj', 'Tiempo', 's', 'lower', '10,76 s', 60, 'Vídeo', 61),
  ('mantis-cortadora', 'Mantis Cortadora', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '306', 60, 'Vídeo + análisis', 62),
  ('lemur-giratorio', 'Lémur Giratorio', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '114', 60, 'Vídeo + análisis', 63),
  ('ciguena-repartidora', 'Cigüeña Repartidora', 'Rapidez y multitarea', 'Puntos', 'puntos', 'higher', '86', 60, 'Vídeo', 64),
  ('trile-del-mapache', 'Trile del Mapache', 'Memoria y lógica', 'Niveles', 'niveles', 'higher', '13', 60, 'Oficial', 65),
  ('gallo-puntual', 'Gallo Puntual', 'Precisión y timing', 'Desviación', 's', 'lower', '0 s', 60, 'Oficial', 66),
  ('foca-malabarista', 'Foca Malabarista', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '41', 60, 'Oficial', 67),
  ('panal-de-la-abeja', 'Panal de la Abeja', 'Memoria y lógica', 'Puntos', 'puntos', 'higher', '148', 60, 'Vídeo', 68),
  ('loro-dictado', 'Loro Dictado', 'Memoria y lógica', 'Puntos', 'puntos', 'higher', '55', 60, 'Oficial', 69),
  ('puas-de-puercoespin', 'Púas de Puercoespín', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '26', 60, 'Vídeo', 70),
  ('panda-lenador', 'Panda Leñador', 'Habilidad y arcade', 'Puntos', 'puntos', 'higher', '130', 60, 'Vídeo', 71)
on conflict (id) do update set
  name = excluded.name, category = excluded.category, metric = excluded.metric, unit = excluded.unit,
  direction = excluded.direction, benchmark = excluded.benchmark, duration_sec = excluded.duration_sec,
  rule_source = excluded.rule_source, rotation_index = excluded.rotation_index;
